### ISSUE TITLE
make sure to comment main parts of code

### ISSUE THREAD

**Issue by ad3429** [Matsonian/prj-rev-bwfs-dasmoto#2]
https://github.com/Matsonian/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html#L8-L32

Make sure to comment the main parts of your HTML in future projects. This becomes increasingly important as your projects become larger and more complex. Here is a quick refresher on commenting in HTML:

<img width="197" alt="html_comment" src="https://user-images.githubusercontent.com/25671399/29130189-155c13d2-7cf7-11e7-8d16-bfe62513ce80.png">

**Comment by Matsonian** [comment]
Thank you!
