### ISSUE TITLE
CSS is clean and succinct 

### ISSUE THREAD

**Issue by ad3429** [Matsonian/prj-rev-bwfs-dasmoto#3]
https://github.com/Matsonian/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/resources/css/index.css#L5-L31

Your css is short, clean and succinct -- great job! One area of improvement here is the comment your main stylings so that when you come back to look at your code after a while, you remember exactly why you chose to style an element a particular way. Here is a quick refresher on commenting in CSS:

<img width="159" alt="css_comment" src="https://user-images.githubusercontent.com/25671399/29130226-2d7f8836-7cf7-11e7-9c0e-3518007c6c72.png">

**Comment by Matsonian** [comment]
Definitely, thank you. Organizing for the future is a definite challenge. ;-)
