### ISSUE TITLE
HTML is nicely organized/structured

### ISSUE THREAD

**Issue by ad3429** [Matsonian/prj-rev-bwfs-dasmoto#4]
https://github.com/Matsonian/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html#L8-L32

You generally followed good coding principles in your HTML, and your code is indented well, readable, and all of your tags are opened/close appropriately. Make sure to keep it up!

**Comment by Matsonian** [comment]
Awesome, thank you.
